### ISSUE TITLE
在配置 OAuth2.0 Access Token 后依然要求输入用户名&密码

### ISSUE THREAD

**Issue by ZoruaFox** [AnYiEE/AwesomeGadgets#21]
如图，测试环境下已在credentials.json设置“ysarchives”为`"OAuth2AccessToken"`，但在pnpm run deploy时依然提示输入Bot password相关信息。

![image](https://github.com/AnYiEE/AwesomeGadgets/assets/96456728/5572ec19-903b-41e0-ab73-e0efd2d788df)

![image](https://github.com/AnYiEE/AwesomeGadgets/assets/96456728/4c6051a2-5ddd-4648-9544-eb403cae0184)

**Comment by AnYiEE** [comment]
我没能复现。

第一个黄色的logging in是在[deploy.ts#L114](https://github.com/AnYiEE/AwesomeGadgets/blob/master/scripts/modules/deploy.ts#L114)被打印的，在它之后就没有对credentials.json的进一步检查了，换言之所有对credentials.json的检查都在看到logging in之前做好了。

但你也可以试试↓

检查一共两次（[deploy.ts#L45](https://github.com/AnYiEE/AwesomeGadgets/blob/master/scripts/modules/deploy.ts#L45)、[deploy.ts#L108](https://github.com/AnYiEE/AwesomeGadgets/blob/master/scripts/modules/deploy.ts#L108)），第二次才会根据情况询问username和password。

所以你可以在[deploy.ts#L108](https://github.com/AnYiEE/AwesomeGadgets/blob/master/scripts/modules/deploy.ts#L108)上方的代码修改为
```ts
} catch (error) {
	console.log({error, config});
```
看看是不是因为105行的`apiInstance.initOAuth()`失败而回退到了用户名/密码的验证形式。
