### ISSUE TITLE
完全相同的package.json部署时出错

### ISSUE THREAD

**Issue by ZoruaFox** [AnYiEE/AwesomeGadgets#25]
上游仓库：qiuwenbaike/QiuwenGadgets

早些时候Upstream Sync工作流出错提示冲突，完全同步package.json后出现如下错误：

![image](https://github.com/AnYiEE/AwesomeGadgets/assets/96456728/263b8794-48ca-4c65-a218-cd8722bfb161)

删除node_module和pnpm-lock.yaml后重新执行pnpm i，出现如下结果：
![image](https://github.com/AnYiEE/AwesomeGadgets/assets/96456728/c56c9fea-12d3-460a-aa4f-4eb0a34da425)

**Comment by AnYiEE** [comment]
这就是因为mw相关的类型定义变动了啊…这是类型报错，和这里有什么关系呢？

**Comment by ZoruaFox** [comment]
> 这就是因为mw相关的类型定义变动了啊…这是类型报错，和这里有什么关系呢？

所以等于是这里需要把相关代码的类型全改一遍，，

但我不明白为啥[同样配置和代码的仓库](https://github.com/qiuwenbaike/QiuwenGadgets)运行的时候没有异常而且upstream sync的工作流可以正常运行

**Comment by ZoruaFox** [comment]
revert to 4.6.0
